"""
Django settings for GiftShop project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import datetime
from django.utils.translation import gettext_lazy as _

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'store': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounting': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vv*)get0%a9qn=w@@$#y(ml@lu3g13g84a^f#0xnb&3gmjhqh0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'mylocal.test']


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'ckeditor',
    'accounting', # New app for accounting system
    'import_export', # Added django-import-export
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GiftShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.global_context',
            ],
        },
    },
]

BASE_URL = 'http://127.0.0.1:8000' # Change this to your actual domain in production

WSGI_APPLICATION = 'GiftShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# WhatsApp Admin Number for Notifications
WHATSAPP_ADMIN_NUMBER = '+201000000000' # !!! IMPORTANT: Change this to your WhatsApp number !!!


LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

GETTEXT_PATH = r'C:\Program Files\gettext-iconv\bin'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Kashier Payment Gateway Settings
KASHIER_MERCHANT_ID = 'MID-36522-572' # Replace with your actual Merchant ID
KASHIER_SERVICE_SECRET_KEY = '60155895-a249-43c2-a169-703350325983'
KASHIER_BASE_URL = 'https://payments.kashier.io' # Base URL for Kashier payments
KASHIER_IFRAME_BASE_URL = "https://widget.kashier.io" # For card tokenization
KASHIER_REDIRECT_URL = 'http://127.0.0.1:8000/kashier/success/' # Your success redirect URL (replace with your domain)
KASHIER_FAILURE_REDIRECT_URL = 'http://127.0.0.1:8000/kashier/failure/' # Your failure redirect URL (replace with your domain)

# UltraMsg WhatsApp API Credentials
ULTRMSG_INSTANCE_ID = 'instance131765'
ULTRMSG_TOKEN = '3nuxgvzon1ip3jll'

# Web Push Notifications Settings
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BFlPZWTZJg3G_Kq6nLNNWz2f-5P_cZJbB-y-sJ_gA-1uI_wB-tZ_3E_vC-7bA_fB_9gJ_jH-kK_lA",
    "VAPID_PRIVATE_KEY": "your_private_key_is_secret",
    "VAPID_ADMIN_EMAIL": "mailto:admin@example.com"
}
# IMPORTANT: In a real production environment, generate your own keys and keep the private key secret.
# You can generate them using: `v-A-p-i-d --gen` (if installed) or other online tools.

JET_SIDE_MENU_ITEMS = [
    {'label': _('لوحة القيادة'), 'url': 'jet-dashboard:dashboard', 'icon': 'fa-tachometer', 'items': []},
    {'label': _('نظام المحاسبة'), 'url': '/accounting/', 'icon': 'fa-calculator', 'items': []}, # New accounting dashboard link
    {'label': _('إعدادات الموقع'), 'url': '/admin/store/siteconfiguration/', 'icon': 'fa-cog', 'items': []},
    {'app_label': 'store', 'items': [
        {'name': 'promotion', 'label': _('العروض الترويجية')},
        {'name': 'category', 'label': _('الفئات')},
        {'name': 'product', 'label': _('المنتجات')},
        {'name': 'customer', 'label': _('العملاء')},
        {'name': 'order', 'label': _('الطلبات')},
        {'name': 'inquiry', 'label': _('الاستفسارات')},
        {'name': 'coupon', 'label': _('كوبونات الخصم')},
        {'name': 'cart', 'label': _('سلال المشتريات')},
        {'name': 'aboutpage', 'label': _('صفحة من نحن')},
    ]},
    {'app_label': 'auth', 'items': [
        {'name': 'user', 'label': _('المستخدمون')},
        {'name': 'group', 'label': _('المجموعات')},
    ]},
]

JET_INDEX_DASHBOARD = 'store.dashboard.CustomIndexDashboard'

LOGGING_CONFIG = 'logging.config.dictConfig'

LOGIN_URL = '/login/'  # Updated to the new custom login URL
LOGIN_REDIRECT_URL = '/account/' # Redirect to account page after login
LOGOUT_REDIRECT_URL = '/' # Redirect to home page after logout

AUTHENTICATION_BACKENDS = [
    'store.auth_backends.UnifiedAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ASGI_APPLICATION = 'GiftShop.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
